import type { SurveyQuestionDefinition, SurveyQuestionId } from "./types";

export const surveyQuestions: SurveyQuestionDefinition[] = [
  {
    id: "professional_role",
    type: "single",
    title: "¿Qué perfil describe mejor tu trabajo actual?",
    description: "Selecciona la opción que mejor represente tu función principal.",
    required: true,
    options: [
      { value: "owner_founder", label: "Propietario/a o fundador/a" },
      { value: "executive", label: "Dirección general o comité ejecutivo" },
      { value: "manager", label: "Mando intermedio o responsable de equipo" },
      { value: "tech_specialist", label: "Tecnología, producto o datos" },
      { value: "marketing_sales", label: "Marketing, ventas o atención al cliente" },
      { value: "operations_security", label: "Operaciones, seguridad, innovación o transformación digital" },
      { value: "consultant_freelance", label: "Consultor/a o profesional autónomo" },
      { value: "employee_other", label: "Empleado/a de otra área" },
      { value: "prefer_not", label: "Prefiero no responder", exclusive: true },
    ],
    rationale: "Permite segmentar resultados por tipo de profesional y responsabilidad funcional.",
    crossTabs: ["company_size", "ai_usage_frequency", "risk_perception"],
  },
  {
    id: "company_size",
    type: "single",
    title: "¿Cuál es el tamaño aproximado de tu organización?",
    required: true,
    options: [
      { value: "solo", label: "Solo yo" },
      { value: "2_10", label: "2 a 10 personas" },
      { value: "11_50", label: "11 a 50 personas" },
      { value: "51_250", label: "51 a 250 personas" },
      { value: "251_1000", label: "251 a 1.000 personas" },
      { value: "1000_plus", label: "Más de 1.000 personas" },
      { value: "unknown", label: "No lo sé", exclusive: true },
      { value: "prefer_not", label: "Prefiero no responder", exclusive: true },
    ],
    rationale: "Permite analizar diferencias de uso y gobernanza según escala operativa.",
    crossTabs: ["governance_maturity", "monitoring_and_shadow_ai", "supplier_dependency_resilience"],
  },
  {
    id: "sector",
    type: "single",
    title: "¿En qué sector trabajas principalmente?",
    required: true,
    options: [
      { value: "technology", label: "Tecnología o software" },
      { value: "professional_services", label: "Servicios profesionales o consultoría" },
      { value: "marketing_media", label: "Marketing, medios o comunicación" },
      { value: "retail_ecommerce", label: "Retail o comercio electrónico" },
      { value: "industry_logistics", label: "Industria, logística o energía" },
      { value: "tourism_hospitality", label: "Turismo, hostelería o restauración" },
      { value: "health_education", label: "Salud, educación o sector público" },
      { value: "finance_legal", label: "Finanzas, seguros o legal" },
      { value: "other", label: "Otro sector" },
      { value: "prefer_not", label: "Prefiero no responder", exclusive: true },
    ],
    rationale: "Ayuda a detectar patrones sectoriales de exposición y madurez.",
    crossTabs: ["shared_information_types", "risk_perception", "supplier_dependency_resilience"],
  },
  {
    id: "country_region",
    type: "single",
    title: "¿Desde qué país o región respondes?",
    description: "El foco inicial es España, pero la encuesta acepta respuestas de otros mercados.",
    required: true,
    options: [
      { value: "es_andalucia", label: "España · Andalucía" },
      { value: "es_cataluna", label: "España · Cataluña" },
      { value: "es_madrid", label: "España · Comunidad de Madrid" },
      { value: "es_valencia", label: "España · Comunidad Valenciana" },
      { value: "es_other", label: "España · Otra comunidad" },
      { value: "eu_other", label: "Otro país de Europa" },
      { value: "latam", label: "Latinoamérica" },
      { value: "other_region", label: "Otra región" },
      { value: "prefer_not", label: "Prefiero no responder", exclusive: true },
    ],
    rationale: "Permite segmentar la muestra por geografía sin pedir datos personales detallados.",
    crossTabs: ["governance_maturity", "ai_usage_frequency"],
  },
  {
    id: "ai_usage_frequency",
    type: "single",
    title: "¿Con qué frecuencia utilizas herramientas de IA en tu trabajo?",
    required: true,
    options: [
      { value: "daily", label: "A diario" },
      { value: "weekly", label: "Varias veces por semana" },
      { value: "monthly", label: "Varias veces al mes" },
      { value: "rarely", label: "De forma esporádica" },
      { value: "never", label: "No las utilizo en el trabajo" },
      { value: "unknown", label: "No lo sé", exclusive: true },
    ],
    rationale: "Responde a la adopción real de IA en el trabajo y sirve como eje principal de segmentación.",
    crossTabs: ["work_account_usage", "shared_information_types", "risk_perception"],
  },
  {
    id: "work_account_usage",
    type: "single",
    title: "Cuando usas IA para tareas profesionales, ¿qué tipo de cuenta utilizas con más frecuencia?",
    required: true,
    options: [
      { value: "company_only", label: "Solo una cuenta corporativa aprobada" },
      { value: "personal_only", label: "Solo una cuenta personal" },
      { value: "mostly_company", label: "Principalmente corporativa, con uso ocasional de cuentas personales" },
      { value: "mostly_personal", label: "Principalmente personal, con acceso limitado a cuentas corporativas" },
      { value: "shared_team", label: "Una cuenta compartida por el equipo" },
      { value: "no_use", label: "No uso IA para el trabajo" },
      { value: "unknown", label: "No lo sé", exclusive: true },
    ],
    rationale: "Permite medir dependencia de cuentas personales y nivel de control formal.",
    crossTabs: ["company_size", "governance_maturity"],
  },
  {
    id: "shared_information_types",
    type: "multi",
    title: "¿Qué tipo de información has compartido o visto compartir en herramientas de IA para tareas de trabajo?",
    description: "Puedes marcar varias opciones. No incluyas ejemplos ni nombres concretos.",
    required: true,
    options: [
      { value: "internal_docs", label: "Documentos internos o borradores" },
      { value: "personal_data", label: "Datos personales de empleados, clientes o leads" },
      { value: "contracts", label: "Contratos, propuestas o documentos legales" },
      { value: "operational_knowledge", label: "Procedimientos, criterios internos o know-how operativo" },
      { value: "strategy", label: "Estrategias, planes o información sensible de negocio" },
      { value: "source_code", label: "Código, consultas o configuraciones técnicas" },
      { value: "none", label: "Ninguno de los anteriores", exclusive: true },
      { value: "unknown", label: "No lo sé", exclusive: true },
      { value: "prefer_not", label: "Prefiero no responder", exclusive: true },
    ],
    rationale: "Mide exposición concreta sin pedir secretos empresariales ni ejemplos confidenciales.",
    crossTabs: ["ai_usage_frequency", "company_size", "sector"],
  },
  {
    id: "governance_maturity",
    type: "single",
    title: "¿Cuál describe mejor la situación de tu organización respecto al uso de IA?",
    required: true,
    options: [
      { value: "none", label: "No existe una política ni pautas claras" },
      { value: "informal", label: "Hay recomendaciones informales, pero no una política formal" },
      { value: "formal_policy", label: "Existe una política formal, pero sin formación sistemática" },
      { value: "policy_training", label: "Existe política formal y formación básica" },
      { value: "policy_training_audit", label: "Existe política formal, formación y algún seguimiento o auditoría" },
      { value: "unknown", label: "No lo sé", exclusive: true },
    ],
    rationale: "Permite estimar madurez de gobernanza y responder al estado de las políticas formales.",
    crossTabs: ["company_size", "monitoring_and_shadow_ai", "supplier_dependency_resilience"],
  },
  {
    id: "vendor_and_safeguard_practices",
    type: "multi",
    title: "¿Qué prácticas aplicas tú o tu organización antes o durante el uso de IA?",
    required: true,
    options: [
      { value: "understand_vendor_terms", label: "Conocemos cómo el proveedor puede usar los datos introducidos" },
      { value: "anonymize_docs", label: "Anonimizamos o resumimos documentos antes de enviarlos" },
      { value: "remove_personal_data", label: "Eliminamos datos personales antes de compartirlos" },
      { value: "avoid_sensitive_uploads", label: "Evitamos subir información sensible salvo necesidad justificada" },
      { value: "approved_tools_only", label: "Limitamos el uso a herramientas aprobadas por la empresa" },
      { value: "none", label: "No aplicamos ninguna de estas prácticas", exclusive: true },
      { value: "unknown", label: "No lo sé", exclusive: true },
    ],
    rationale: "Agrupa controles clave para evaluar conocimiento del proveedor y hábitos de reducción de riesgo.",
    crossTabs: ["shared_information_types", "governance_maturity"],
  },
  {
    id: "monitoring_and_shadow_ai",
    type: "single",
    title: "¿Cuál de estas situaciones se acerca más a la realidad de tu organización?",
    required: true,
    options: [
      { value: "logs_and_detected", label: "Se registra o audita el uso de IA y ya se han detectado casos de Shadow AI" },
      { value: "logs_no_detected", label: "Se registra o audita el uso de IA, pero no se han detectado casos de Shadow AI" },
      { value: "no_logs_detected", label: "No se registra de forma sistemática, pero sí se han detectado casos de Shadow AI" },
      { value: "no_logs_no_detected", label: "No se registra de forma sistemática y no se han detectado casos" },
      { value: "unknown", label: "No lo sé", exclusive: true },
    ],
    rationale: "Permite medir observabilidad y presencia de Shadow AI con una sola pregunta.",
    crossTabs: ["governance_maturity", "company_size"],
  },
  {
    id: "supplier_dependency_resilience",
    type: "single",
    title: "Si vuestra herramienta o modelo principal de IA dejara de estar disponible durante 30 días, ¿qué ocurriría?",
    required: true,
    options: [
      { value: "no_dependency", label: "Tendríamos poco impacto porque usamos varias alternativas o apenas dependemos de ella" },
      { value: "manageable_switch", label: "Habría impacto, pero podríamos cambiar de proveedor o proceso sin grandes problemas" },
      { value: "significant_delay", label: "Se retrasarían tareas importantes durante varias semanas" },
      { value: "major_disruption", label: "Se verían afectadas operaciones clave o entregas al cliente" },
      { value: "critical_stop", label: "Parte del trabajo quedaría prácticamente bloqueado" },
      { value: "not_applicable", label: "No aplica porque no usamos IA de forma relevante" },
      { value: "unknown", label: "No lo sé", exclusive: true },
    ],
    rationale: "Mide dependencia de proveedor y resiliencia operativa frente a una indisponibilidad prolongada.",
    crossTabs: ["ai_usage_frequency", "work_account_usage", "governance_maturity"],
  },
  {
    id: "risk_perception",
    type: "scale",
    title: "En una escala del 1 al 5, ¿qué nivel de riesgo percibes en el uso actual de IA en tu entorno de trabajo?",
    description: "1 significa riesgo muy bajo y 5 riesgo muy alto.",
    required: true,
    options: [
      { value: "1", label: "1 · Muy bajo" },
      { value: "2", label: "2 · Bajo" },
      { value: "3", label: "3 · Medio" },
      { value: "4", label: "4 · Alto" },
      { value: "5", label: "5 · Muy alto" },
      { value: "unknown", label: "No lo sé", exclusive: true },
    ],
    rationale: "Recoge percepción de riesgo para compararla con comportamientos y controles reales.",
    crossTabs: ["shared_information_types", "vendor_and_safeguard_practices", "supplier_dependency_resilience"],
  },
];

export const surveyQuestionMap = surveyQuestions.reduce<Record<SurveyQuestionId, SurveyQuestionDefinition>>(
  (acc, question) => {
    acc[question.id] = question;
    return acc;
  },
  {} as Record<SurveyQuestionId, SurveyQuestionDefinition>,
);

export const totalSurveyQuestions = surveyQuestions.length;
